name: Sphinx Documentation Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs docs/_build/html # 构建 HTML 文档
      
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-html
          path: docs/_build/html
